### ISSUE TITLE
Release next version?

### ISSUE THREAD

**Issue by Firstyear** [csnewman/libnss-rs#6]
Hi there,

I noticed that the version on crates.io is different from what's in github here. I think mainly this in the group and passwd traits and the responses they provide (the crates.io version uses Option, not Response). It would be great if you could make a release of this to crates.io please!

**Comment by edevil** [comment]
This seems like a good idea. What do you think @csnewman?

**Comment by Firstyear** [comment]
Hey @csnewman it's been a while since I opened this. I'm pretty invested in maintaining and improving this library, so if it's okay, can I help maintain it with you? How would that work for you?

**Comment by csnewman** [comment]
I'll create a release later today.

@Firstyear I'm open to MRs and I can create a gitter if you want a place for discussions.

**Comment by Firstyear** [comment]
Ahh I was more worried because it took a while for you to respond, and I didn't want the project to be stale. I'll submit PR's in the future then, thanks!

**Comment by csnewman** [comment]
`0.3.0` has been released.
